feat(gobot): add idempotency to the bot
csunibo/infrastructure pull request #4
Opened 2023-04-14 19:44 UTC by Flecart

2023-04-14 19:45 UTC, Flecart commented
una cosa strana è che non trova la password, provalo comunque

2023-04-14 19:56 UTC, foxyseta reviewed
Forse hai perso le modifiche dell'ultimo commit su main?

2023-04-14 19:58 UTC, lucat1 requested changes
Hai invertito la castistica nei `when`

2023-04-14 20:13 UTC, Flecart commented
> Forse hai perso le modifiche dell'ultimo commit su main?

no queste ci dovrebbero essere

2023-04-14 20:24 UTC, foxyseta commented
> > Forse hai perso le modifiche dell'ultimo commit su main?
> 
> no queste ci dovrebbero essere

Le chiavi coppie valore rimosse nel diff dico

2023-04-15 06:46 UTC, Flecart commented
> > > Forse hai perso le modifiche dell'ultimo commit su main?
> > 
> > 
> > no queste ci dovrebbero essere
> 
> Le chiavi coppie valore rimosse nel diff dico

Quali chiavi coppie?

2023-04-15 07:08 UTC, lucat1 approved these changes
Per me così va bene, aspettiamo di capire cosa non torna a @foxyseta .

2023-04-15 08:38 UTC, foxyseta commented
single_branch e enabled.

2023-04-15 19:18 UTC, lucat1 commented
`single_branch` non so se serve. l’ultimo enabled si lo metterei.

2023-04-15 19:27 UTC, Flecart commented
pushato

2023-04-15 19:40 UTC, foxyseta approved these changes

2023-04-15 19:40 UTC, merged