GitHub bot
csunibo/infrastructure pull request #5
Opened 2023-06-02 18:12 UTC by Flecart

La cosa brutta è che mi sono ritrovato a compilare python dal source :P.
Tutta la lista delle dipendenze è copiata incollata da un sito.
Il fatto è che debian ha 3.9 al massimo, che sta troppo stable, online ho trovato solo compilazione da source per debian, per ubuntu c'erano dei PPA, che giustamente non andavano su debian.
Btw ho provato a runnare con 3.9 e proprio non è compatibile, necessita di almeno 3.10 per le cose di type hinting di python.

Poi poetry sarebbe solamente per sviluppo, ma sono stato pigro e lo ho messo anche qui, in teoria dovrebbe bastare scaricarsi un package da csunibo/csgitbot, per installare ma c'erano ancora delle cose che non riuscivo a gestire, quindi mi sono messo poetry direttamente su quella macchina.

2023-06-02 22:36 UTC, lucat1 commented
Sono nel letto e non ho guardato al codice. Ma due commenti che mi vengono solo leggendo il tuo messaggio:
1. direi che bisogna usare pip anzi che poetry. Va bene per sviluppo usa il package manager che vuoi ma per installare usiamo quello standard e built in. Genera in qualche modo il requirements.txt se non lo hai già con poetry
2. Per la versione di python, due soluzioni: tra qualche giorno rilasciano la nuova versione di debian (bookworm) che sicuramente ha python più aggiornato. Anche se rimanessimo su bullseye, guarda alla repository di debian bullseye-backports, probabilmente li hanno una versione più aggiornata.

2023-10-14 22:47 UTC, foxyseta commented
Chiuso non essendo csgitbot più attivamente sviluppato al momento. La branch comunque per comodità non la cancelleri almeno per ora.

2023-10-15 15:10 UTC, Flecart commented
ok

2024-02-03 20:40 UTC, samuelemusiani requested changes
Qualcosina qua e la, per il resto tutto a posto

2024-02-03 20:40 UTC, samuelemusiani commented on files/csgitbot/.env.j2
Eviterei di usare un nome che inizia per `.` perché risulterebbe un file nascosto e non è molto chiaro. Visto che tanto durante la copia sei libero di cambiargli nome lo rinominerei soltanto a `env.j2`

2024-02-03 20:40 UTC, samuelemusiani commented on tasks/csgitbot.yaml
> +    var: python_version
Non penso che serva tutta questa parte

2024-02-03 20:40 UTC, samuelemusiani commented on tasks/csgitbot.yaml
> +- name: check if virtual environment exists
Roba piccolissima: se riesci a mettere la maiuscola su "check"
```suggestion
- name: Check if virtual environment exists
```

2024-02-03 20:40 UTC, samuelemusiani commented on tasks/csgitbot.yaml
> +    var: python3_path.stdout
Direi che anche questo non ti serve

2024-02-03 20:40 UTC, samuelemusiani commented on tasks/csgitbot.yaml
> +    client_secret: "{{ lookup('file', 'passwords/csgitbot_secret') }}"
Questi tre li puoi fare tutti insieme! Poi cambia nome :)
```suggestion
- name: Read the bot secrets
  ansible.builtin.set_fact:
    github_token: "{{ lookup('file', 'passwords/csgitbot_github_secret') }}"
    client_id: "{{ lookup('file', 'passwords/csgitbot_id') }}"
    client_secret: "{{ lookup('file', 'passwords/csgitbot_secret') }}"
```

2024-02-03 20:43 UTC, Flecart commented on tasks/csgitbot.yaml
> +    var: python_version
Yup, era roba legacy per debuggare

2024-02-03 20:46 UTC, Flecart commented on tasks/csgitbot.yaml
> +    client_secret: "{{ lookup('file', 'passwords/csgitbot_secret') }}"
Carino non lo sapevo

2024-02-03 20:50 UTC, samuelemusiani requested changes
L'ultimissima cosa che credevo di aver scritto ma evidentemente mi ero perso

2024-02-03 20:50 UTC, samuelemusiani commented on files/csgitbot/bot.service
> +Description=Informabot
Mi sembrava di averlo scritto prima ma evidentemente me lo sono perso, c'è questo nome da cambiare
```suggestion
Description=CSGitbot
```

2024-02-03 21:29 UTC, samuelemusiani approved these changes

2024-02-03 21:30 UTC, merged